export type Stats = {
  Attack?: number;
  Believing?: number;
  Constitution?: number;
  Defense?: number;
  Emotion?: number;
  Forgiving?: number;
  Grit?: number;
  Heart?: number;
  Imagination?: number;
  Jovial?: number;
  Kindness?: number;
  Love?: number;
  Magic?: number;
  Navigation?: number;
  Openness?: number;
  Piety?: number;
  Questioning?: number;
  Responsibility?: number;
  Strength?: number;
  Toughness?: number;
  Utilitarianism?: number;
  Vengefulness?: number;
  Will?: number;
  Xenophobia?: number;
  Yeehaw?: number;
  Zeal?: number;
};
